"""The admin page's JavaScript is generated by Python, so it gets browser tests.

WHY THIS FILE EXISTS. `_admin_page_html` builds its `<script>` blocks inside a
Python f-string. That means every backslash in the JavaScript is read by Python
first: a single `\\n` written in the source becomes a REAL newline in the output,
which splits a JS regex literal across two lines and throws a SyntaxError that
kills the entire script block. The page still renders, every Python test still
passes, and the feature is silently dead.

That happened twice while this picker was being written -- once in the regex
itself and once in the comment explaining the regex. No assertion about the HTML
string can catch it. Only a real JS parser can, so these tests load the rendered
page in a headless browser and fail on any page error.

Driven from a temp file over file://, the same way
tests/test_frontend_error_detail_surfacing.py drives the demo page: no server,
no port 8000 or 8947, no Scryfall calls (fetch is stubbed in-page).
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from playwright.sync_api import sync_playwright

from rulesagent.api import main as api_main

REPO = Path(__file__).resolve().parents[1]

STUB_FETCH = """
window.__acCalls = [];
window.fetch = function (url) {
  window.__acCalls.push(url);
  return Promise.resolve({ ok: true, json: function () {
    return Promise.resolve({ suggestions: [
      "Emrakul, the Promised End", "Emrakul, the Aeons Torn", "Emrakul's Evangel"] });
  }});
};
"""


def _seeded_db(tmp_path: Path) -> Path:
    """A demo database with one unapproved candidate question."""
    db = tmp_path / "demo.db"
    conn = sqlite3.connect(db)
    conn.execute(
        "CREATE TABLE events (id INTEGER PRIMARY KEY AUTOINCREMENT, "
        "code_id INTEGER, ts TEXT NOT NULL, kind TEXT NOT NULL, ip_hash TEXT, "
        "question TEXT, answered INTEGER, input_tokens INTEGER, "
        "output_tokens INTEGER, cost_usd REAL, latency_ms INTEGER)"
    )
    conn.execute(
        "INSERT INTO events (code_id, ts, kind, ip_hash, question, answered) "
        "VALUES (1, '2026-07-28T10:00:00+00:00', 'query', 'h', "
        "'does a copy of a token die when the original does', 1)"
    )
    conn.commit()
    conn.close()
    return db


def _page_file(tmp_path: Path, monkeypatch) -> Path:
    monkeypatch.setattr(api_main, "DEMO_DB", _seeded_db(tmp_path))
    out = tmp_path / "admin.html"
    out.write_text(api_main._admin_page_html(), encoding="utf-8")
    return out


@pytest.fixture(scope="module")
def browser():
    with sync_playwright() as p:
        b = p.chromium.launch()
        yield b
        b.close()


def _open(browser, path: Path):
    page = browser.new_page()
    errors: list[str] = []
    page.on("pageerror", lambda e: errors.append(str(e)))
    page.goto(path.resolve().as_uri())
    page.add_script_tag(content=STUB_FETCH)
    return page, errors


def test_admin_page_javascript_parses(browser, tmp_path, monkeypatch):
    """The regression test for the whole bug class: any SyntaxError in a
    generated script block shows up here and nowhere else."""
    page, errors = _open(browser, _page_file(tmp_path, monkeypatch))
    page.wait_for_timeout(150)
    assert errors == [], f"JavaScript errors on the admin page: {errors}"
    page.close()


def test_typing_an_at_token_queries_the_autocomplete_endpoint(browser, tmp_path,
                                                              monkeypatch):
    page, errors = _open(browser, _page_file(tmp_path, monkeypatch))
    page.eval_on_selector(
        ".candidate-textarea",
        """ta => {
            ta.focus();
            ta.value = "does @emra die when the original does";
            ta.selectionStart = ta.selectionEnd = "does @emra".length;
            ta.dispatchEvent(new Event('input', {bubbles: true}));
        }""")
    page.wait_for_timeout(400)
    assert page.evaluate("window.__acCalls") == ["/cards/autocomplete?q=emra"]
    assert errors == []
    page.close()


def test_suggestions_render_and_enter_inserts_bracket_syntax(browser, tmp_path,
                                                             monkeypatch):
    """Bracket syntax is the point: the answer pipeline only resolves a card
    written as [Exact Card Name], so a correction that inserts bare text would
    produce an approved example that never looks the card up."""
    page, errors = _open(browser, _page_file(tmp_path, monkeypatch))
    page.eval_on_selector(
        ".candidate-textarea",
        """ta => {
            ta.focus();
            ta.value = "does @emra die when the original does";
            ta.selectionStart = ta.selectionEnd = "does @emra".length;
            ta.dispatchEvent(new Event('input', {bubbles: true}));
        }""")
    page.wait_for_timeout(400)

    options = page.eval_on_selector_all(".ac-item", "els => els.map(e => e.textContent)")
    assert options == ["Emrakul, the Promised End", "Emrakul, the Aeons Torn",
                       "Emrakul's Evangel"]

    page.eval_on_selector(
        ".candidate-textarea",
        """ta => ta.dispatchEvent(new KeyboardEvent('keydown',
            {key: 'Enter', bubbles: true, cancelable: true}))""")
    page.wait_for_timeout(100)

    value = page.eval_on_selector(".candidate-textarea", "ta => ta.value")
    assert value == "does [Emrakul, the Promised End] die when the original does", (
        "expected the @token replaced by bracket syntax with exactly one space")
    assert errors == []
    page.close()


def test_escape_closes_the_menu_without_changing_the_text(browser, tmp_path,
                                                          monkeypatch):
    page, errors = _open(browser, _page_file(tmp_path, monkeypatch))
    page.eval_on_selector(
        ".candidate-textarea",
        """ta => {
            ta.focus();
            ta.value = "does @emra die";
            ta.selectionStart = ta.selectionEnd = "does @emra".length;
            ta.dispatchEvent(new Event('input', {bubbles: true}));
        }""")
    page.wait_for_timeout(400)
    page.eval_on_selector(
        ".candidate-textarea",
        """ta => ta.dispatchEvent(new KeyboardEvent('keydown',
            {key: 'Escape', bubbles: true, cancelable: true}))""")
    page.wait_for_timeout(100)

    assert page.eval_on_selector(".ac-menu", "m => getComputedStyle(m).display") == "none"
    assert page.eval_on_selector(".candidate-textarea", "ta => ta.value") == "does @emra die"
    assert errors == []
    page.close()


def test_short_token_does_not_call_the_endpoint(browser, tmp_path, monkeypatch):
    """Scryfall wants two characters; one keystroke must not hit it."""
    page, errors = _open(browser, _page_file(tmp_path, monkeypatch))
    page.eval_on_selector(
        ".candidate-textarea",
        """ta => {
            ta.focus();
            ta.value = "does @e die";
            ta.selectionStart = ta.selectionEnd = "does @e".length;
            ta.dispatchEvent(new Event('input', {bubbles: true}));
        }""")
    page.wait_for_timeout(400)
    assert page.evaluate("window.__acCalls") == []
    assert errors == []
    page.close()
